export const data = [
  {
    contract: {
      address: "0x07ce5d64b7b845c8ff645e9a3825f94e6bdd82f1",
      name: "JustCubes",
      symbol: "CUBE",
      totalSupply: "4444",
      tokenType: "ERC721",
      openSea: {
        floorPrice: 0.044,
        collectionName: "JustCubesNFT",
        safelistRequestStatus: "verified",
        imageUrl:
          "https://i.seadn.io/gcs/files/20a565537c2b7ae2e3e1b87f2ebf48d2.png?w=500&auto=format",
        description:
          "- Improve TX speeds, secure hype mints, and snipe with ease using our HyperNode. \n- ETH minting bot coming soon\n- Track whales, analyze projects with access to Nansen, and improve your investing.\n\nWARNING: These images may potentially trigger seizures for people with photosensitive epilepsy. Viewer discretion is advised.\n\n4444 Just Cubes NFTs created by Just Cubes LLC™ to shake up the metaverse and change what it means to have utility behind a project. Our community is not only a place to improve yourself as an investor and trader but it's a place to hangout and have genuine connection within the space.",
        externalUrl: "https://bit.ly/JustCubesNFTWebsite",
        twitterUsername: "JustCubesNFT",
        discordUrl: "https://discord.gg/justcubesnft",
        lastIngestedAt: "2023-03-07T07:25:20.000Z",
      },
      contractDeployer: "0xd613c451a22346d1eaa2fffb72836b1f24b5b47f",
      deployedBlockNumber: 14345626,
    },
    tokenId: "4089",
    tokenType: "ERC721",
    title: "Cube #4090",
    description:
      "4444 Just Cubes NFTs created by Just Cubes LLC™ to shake up the metaverse and change what it means to have utility behind a project. Our community is not only a place to improve yourself as an investor and trader but it's a place to hangout and have genuine connection within the space.",
    timeLastUpdated: "2023-03-05T13:44:39.146Z",
    rawMetadata: {
      date: "1647097892",
      image:
        "https://gateway.pinata.cloud/ipfs/QmV5S8Y3YQr3rEw5BYgXpWbyaHkY1p55Lkjy3C1L6w1hcs/4089.gif",
      dna: " 11 4 13 16 0 13 ",
      name: "Cube #4090",
      description:
        "4444 Just Cubes NFTs created by Just Cubes LLC™ to shake up the metaverse and change what it means to have utility behind a project. Our community is not only a place to improve yourself as an investor and trader but it's a place to hangout and have genuine connection within the space.",
      edition: "4089",
      attributes: [
        {
          value: "Peach Swirl",
          trait_type: "PastelBackground",
        },
        {
          value: "Buttermilk",
          trait_type: "PastelLeftFace",
        },
        {
          value: "Lime",
          trait_type: "PastelRightFace",
        },
        {
          value: "Pistachio",
          trait_type: "PastelTop",
        },
        {
          value: "Outline",
          trait_type: "Outline",
        },
        {
          value: "Happy",
          trait_type: "Face",
        },
      ],
    },
    tokenUri: {
      gateway:
        "https://ipfs.io/ipfs/QmUqkHyzB5HwQMEozpvCobK8oixKM1QUjqLDyF4oZW4b8d/4089",
      raw: "https://gateway.pinata.cloud/ipfs/QmUqkHyzB5HwQMEozpvCobK8oixKM1QUjqLDyF4oZW4b8d/4089",
    },
    media: [
      {
        gateway:
          "https://nft-cdn.alchemy.com/eth-mainnet/d015e0c11977305aeb8c732e403e151e",
        thumbnail:
          "https://res.cloudinary.com/alchemyapi/image/upload/thumbnailv2/eth-mainnet/d015e0c11977305aeb8c732e403e151e",
        raw: "https://gateway.pinata.cloud/ipfs/QmV5S8Y3YQr3rEw5BYgXpWbyaHkY1p55Lkjy3C1L6w1hcs/4089.gif",
        format: "gif",
        bytes: 53413,
      },
    ],
    balance: 1,
  },
  {
    contract: {
      address: "0x101079dd59af1e67e8e4e75aba25b5b5172ba0b3",
      name: "MetaArtz Genesis Pass",
      symbol: "Artz",
      totalSupply: "176",
      tokenType: "ERC721",
      openSea: {
        floorPrice: 0,
        collectionName: "MetaArtz Genesis Pass",
        safelistRequestStatus: "not_requested",
        imageUrl:
          "https://i.seadn.io/gae/_PiLQxeIHEjlc3eQO09FssNYy8SwOKT5GwlurD6bbR9AbFYY42WJSF3OIaBNWi-HV_S5zUvz9k7OiSb5DIKb3plIm2P5ENIlATxrSDc?w=500&auto=format",
        description:
          "We specialize in advanced Ai technology, blockchain smart contracts, and create 100% art NFT’s generated from AI. We love & support our communities involvement!!! Our first collection was generated by the founders of MetaArtz, but the future collections are going to be decided on by our communities input. The future direction of MetaArtz will be in your hands!",
        externalUrl: "https://metaartz.com",
        discordUrl: "https://discord.gg/tW4xFr2A",
        lastIngestedAt: "2023-02-26T08:54:58.000Z",
      },
      contractDeployer: "0xedb583e5a92054184f504183271bcac372ea5d8d",
      deployedBlockNumber: 14632507,
    },
    tokenId: "72",
    tokenType: "ERC721",
    title: "MetaArtz Genesis Pass #72",
    description:
      "The MetaArtz Genesis Pass Gives you Access To All Future Collection! Whitelisting And Drops For All Future Projects!",
    timeLastUpdated: "2023-02-10T13:13:28.592Z",
    rawMetadata: {
      name: "MetaArtz Genesis Pass #72",
      description:
        "The MetaArtz Genesis Pass Gives you Access To All Future Collection! Whitelisting And Drops For All Future Projects!",
      image: "https://api.metaartz.com/img/072.png",
      attributes: [
        {
          traitType: "Rarity",
          value: "Genesis Pass",
        },
      ],
    },
    tokenUri: {
      gateway: "https://api.metaartz.com/72",
      raw: "https://api.metaartz.com/72",
    },
    media: [
      {
        gateway:
          "https://nft-cdn.alchemy.com/eth-mainnet/46e2882f4a5e60337886d577592b7e96",
        thumbnail:
          "https://res.cloudinary.com/alchemyapi/image/upload/thumbnailv2/eth-mainnet/46e2882f4a5e60337886d577592b7e96",
        raw: "https://api.metaartz.com/img/072.png",
        format: "png",
        bytes: 975517,
      },
    ],
    balance: 1,
  },
  {
    contract: {
      address: "0x5469d688ff5d50a254babd2f0f3a04e6c1bd59a9",
      name: "The Fool NFT",
      symbol: "TF",
      totalSupply: "1034",
      tokenType: "ERC721",
      openSea: {
        collectionName: "The Fool NFT",
        safelistRequestStatus: "not_requested",
        imageUrl:
          "https://i.seadn.io/gae/cO8kqLR8X176v93P4Gp8UcSV7GkRWHl9lIAzrGviWEQrmUBkmUJ8OG1G5S73E1ouWmXPQhdS4jxmPxU778v1cyz5hDYiI5N8bHu-uQ?w=500&auto=format",
        description:
          "There's no roadmap for this project,\n\nit's just a fucking mockery of NFT, is like Doge Coin mocking BTC.\n\nAnyone can publish a set of NFT JPG images at very low cost,\n\nHell, someone would pay millions of dollars for a JGP image!\n\nSo does this JPG image actually improve your real life in any way?\n\nMillions of dollars may not matter to the rich,\n\nBut for fools, it's stupid to spend all your money on a useless JPG.",
        lastIngestedAt: "2023-03-06T08:57:38.000Z",
      },
      contractDeployer: "0x4e7d70ece7d4a1d3f9837942e3fdaa3ece051a84",
      deployedBlockNumber: 14332401,
    },
    tokenId: "954",
    tokenType: "ERC721",
    title: "",
    description: "",
    timeLastUpdated: "2022-11-29T07:54:25.841Z",
    rawMetadata: {
      image: "ipfs://QmPamiYDqR27jbUM7yHY8GXYJnN3DqtxqyXfcbdCBs91D1",
      attributes: [
        {
          value: "Bored",
          trait_type: "Mouth",
        },
        {
          value: "Yellow",
          trait_type: "Background",
        },
        {
          value: "Bone Tee",
          trait_type: "Clothes",
        },
        {
          value: "Sea Captain's Hat",
          trait_type: "Hat",
        },
        {
          value: "Gray",
          trait_type: "Fur",
        },
        {
          value: "Hypnotized",
          trait_type: "Eyes",
        },
      ],
    },
    tokenUri: {
      gateway:
        "https://ipfs.io/ipfs/QmeSjSinHpPnmXmspMjwiXyN6zS4E9zccariGR3jxcaWtq/954",
      raw: "ipfs://QmeSjSinHpPnmXmspMjwiXyN6zS4E9zccariGR3jxcaWtq/954",
    },
    media: [
      {
        gateway:
          "https://nft-cdn.alchemy.com/eth-mainnet/0a4582d3401ac4f669728270ccd3d6f1",
        thumbnail:
          "https://res.cloudinary.com/alchemyapi/image/upload/thumbnailv2/eth-mainnet/0a4582d3401ac4f669728270ccd3d6f1",
        raw: "ipfs://QmPamiYDqR27jbUM7yHY8GXYJnN3DqtxqyXfcbdCBs91D1",
        format: "png",
        bytes: 135995,
      },
    ],
    balance: 1,
  },
  {
    contract: {
      address: "0x82cb9d20862641301c987f0b096086d32bc11b65",
      name: "AStrandOfHair",
      symbol: "ASOH",
      totalSupply: "10358",
      tokenType: "ERC721",
      openSea: {
        floorPrice: 0,
        collectionName: "AStrandOfHair",
        safelistRequestStatus: "approved",
        imageUrl:
          "https://i.seadn.io/gcs/files/5aa37f4f867ad6f1d5ab710f67f6cfdd.jpg?w=500&auto=format",
        description:
          "It's a metaverse built by wizards. From just a strand of hair to the entire world. We are not just a meme, we are a culture strongly rooted by our community. ",
        externalUrl: "https://astrandofhair.xyz/",
        twitterUsername: "Hair_xyz",
        lastIngestedAt: "2023-02-23T08:27:10.000Z",
      },
      contractDeployer: "0xc4c2a776a352a8994be83d2ef2bb4a9604dc6e97",
      deployedBlockNumber: 15210942,
    },
    tokenId: "20",
    tokenType: "ERC721",
    title: "AStrandOfHair #20",
    description: "",
    timeLastUpdated: "2023-03-05T04:20:39.686Z",
    rawMetadata: {
      name: "AStrandOfHair #20",
      description: "",
      image: "ipfs://QmS813MTWh2N8zJH3edrYDVUrVX5WfPraDiK1119tXow8V/20.png",
      attributes: [
        {
          value: "berlin blue",
          trait_type: "Background",
        },
        {
          value: "light blue",
          trait_type: "Shadow",
        },
        {
          value: "salvina",
          trait_type: "Witch",
        },
        {
          value: "blue",
          trait_type: "Smag",
        },
        {
          value: "green",
          trait_type: "Pot",
        },
        {
          value: "gray - stars",
          trait_type: "Soul",
        },
        {
          value: "plant",
          trait_type: "Medium",
        },
        {
          value: "green - subterranean",
          trait_type: "Stealer",
        },
        {
          value: "horn",
          trait_type: "Loot",
        },
        {
          value: "dark blue - bubble hair",
          trait_type: "Hair",
        },
      ],
    },
    tokenUri: {
      gateway:
        "https://ipfs.io/ipfs/QmTUnRhkS1f5TxY1tCJMYhG2igkjVhKsppYYBNpPv4bSvN/20.json",
      raw: "ipfs://QmTUnRhkS1f5TxY1tCJMYhG2igkjVhKsppYYBNpPv4bSvN/20.json",
    },
    media: [
      {
        gateway:
          "https://nft-cdn.alchemy.com/eth-mainnet/2e96142d9150ec793d65aed16ac1151c",
        thumbnail:
          "https://res.cloudinary.com/alchemyapi/image/upload/thumbnailv2/eth-mainnet/2e96142d9150ec793d65aed16ac1151c",
        raw: "ipfs://QmS813MTWh2N8zJH3edrYDVUrVX5WfPraDiK1119tXow8V/20.png",
        format: "png",
        bytes: 2569116,
      },
    ],
    balance: 1,
  },
  {
    contract: {
      address: "0x82cb9d20862641301c987f0b096086d32bc11b65",
      name: "AStrandOfHair",
      symbol: "ASOH",
      totalSupply: "10358",
      tokenType: "ERC721",
      openSea: {
        floorPrice: 0,
        collectionName: "AStrandOfHair",
        safelistRequestStatus: "approved",
        imageUrl:
          "https://i.seadn.io/gcs/files/5aa37f4f867ad6f1d5ab710f67f6cfdd.jpg?w=500&auto=format",
        description:
          "It's a metaverse built by wizards. From just a strand of hair to the entire world. We are not just a meme, we are a culture strongly rooted by our community. ",
        externalUrl: "https://astrandofhair.xyz/",
        twitterUsername: "Hair_xyz",
        lastIngestedAt: "2023-02-23T08:27:10.000Z",
      },
      contractDeployer: "0xc4c2a776a352a8994be83d2ef2bb4a9604dc6e97",
      deployedBlockNumber: 15210942,
    },
    tokenId: "21",
    tokenType: "ERC721",
    title: "AStrandOfHair #21",
    description: "",
    timeLastUpdated: "2023-02-10T13:19:29.389Z",
    rawMetadata: {
      name: "AStrandOfHair #21",
      description: "",
      image: "ipfs://QmS813MTWh2N8zJH3edrYDVUrVX5WfPraDiK1119tXow8V/21.png",
      attributes: [
        {
          value: "dark green",
          trait_type: "Background",
        },
        {
          value: "black",
          trait_type: "Shadow",
        },
        {
          value: "alverta",
          trait_type: "Witch",
        },
        {
          value: "ice blue",
          trait_type: "Smag",
        },
        {
          value: "copper",
          trait_type: "Pot",
        },
        {
          value: "brown bubble",
          trait_type: "Soul",
        },
        {
          value: "plant",
          trait_type: "Medium",
        },
        {
          value: "pink - beggar",
          trait_type: "Stealer",
        },
        {
          value: "wathet - brain",
          trait_type: "Loot",
        },
        {
          value: "green - bacterial hair",
          trait_type: "Hair",
        },
      ],
    },
    tokenUri: {
      gateway:
        "https://ipfs.io/ipfs/QmTUnRhkS1f5TxY1tCJMYhG2igkjVhKsppYYBNpPv4bSvN/21.json",
      raw: "ipfs://QmTUnRhkS1f5TxY1tCJMYhG2igkjVhKsppYYBNpPv4bSvN/21.json",
    },
    media: [
      {
        gateway:
          "https://nft-cdn.alchemy.com/eth-mainnet/f69c04e0f7e568467eaf6262dbec1dba",
        thumbnail:
          "https://res.cloudinary.com/alchemyapi/image/upload/thumbnailv2/eth-mainnet/f69c04e0f7e568467eaf6262dbec1dba",
        raw: "ipfs://QmS813MTWh2N8zJH3edrYDVUrVX5WfPraDiK1119tXow8V/21.png",
        format: "png",
        bytes: 2403636,
      },
    ],
    balance: 1,
  },
  {
    contract: {
      address: "0x82cb9d20862641301c987f0b096086d32bc11b65",
      name: "AStrandOfHair",
      symbol: "ASOH",
      totalSupply: "10358",
      tokenType: "ERC721",
      openSea: {
        floorPrice: 0,
        collectionName: "AStrandOfHair",
        safelistRequestStatus: "approved",
        imageUrl:
          "https://i.seadn.io/gcs/files/5aa37f4f867ad6f1d5ab710f67f6cfdd.jpg?w=500&auto=format",
        description:
          "It's a metaverse built by wizards. From just a strand of hair to the entire world. We are not just a meme, we are a culture strongly rooted by our community. ",
        externalUrl: "https://astrandofhair.xyz/",
        twitterUsername: "Hair_xyz",
        lastIngestedAt: "2023-02-23T08:27:10.000Z",
      },
      contractDeployer: "0xc4c2a776a352a8994be83d2ef2bb4a9604dc6e97",
      deployedBlockNumber: 15210942,
    },
    tokenId: "22",
    tokenType: "ERC721",
    title: "AStrandOfHair #22",
    description: "",
    timeLastUpdated: "2023-01-22T04:49:36.111Z",
    rawMetadata: {
      name: "AStrandOfHair #22",
      description: "",
      image: "ipfs://QmS813MTWh2N8zJH3edrYDVUrVX5WfPraDiK1119tXow8V/22.png",
      attributes: [
        {
          value: "blue violet",
          trait_type: "Background",
        },
        {
          value: "purple grey",
          trait_type: "Shadow",
        },
        {
          value: "ishmerai",
          trait_type: "Witch",
        },
        {
          value: "ice blue",
          trait_type: "Smag",
        },
        {
          value: "patch",
          trait_type: "Pot",
        },
        {
          value: "brown bubble",
          trait_type: "Soul",
        },
        {
          value: "plant",
          trait_type: "Medium",
        },
        {
          value: "purple - goblin",
          trait_type: "Stealer",
        },
        {
          value: "crown",
          trait_type: "Loot",
        },
        {
          value: "prasinous - tragi",
          trait_type: "Hair",
        },
      ],
    },
    tokenUri: {
      gateway:
        "https://ipfs.io/ipfs/QmTUnRhkS1f5TxY1tCJMYhG2igkjVhKsppYYBNpPv4bSvN/22.json",
      raw: "ipfs://QmTUnRhkS1f5TxY1tCJMYhG2igkjVhKsppYYBNpPv4bSvN/22.json",
    },
    media: [
      {
        gateway:
          "https://nft-cdn.alchemy.com/eth-mainnet/5d5cee8929cbbfb72857a477e490df35",
        thumbnail:
          "https://res.cloudinary.com/alchemyapi/image/upload/thumbnailv2/eth-mainnet/5d5cee8929cbbfb72857a477e490df35",
        raw: "ipfs://QmS813MTWh2N8zJH3edrYDVUrVX5WfPraDiK1119tXow8V/22.png",
        format: "png",
        bytes: 2502483,
      },
    ],
    balance: 1,
  },
  {
    contract: {
      address: "0x82cb9d20862641301c987f0b096086d32bc11b65",
      name: "AStrandOfHair",
      symbol: "ASOH",
      totalSupply: "10358",
      tokenType: "ERC721",
      openSea: {
        floorPrice: 0,
        collectionName: "AStrandOfHair",
        safelistRequestStatus: "approved",
        imageUrl:
          "https://i.seadn.io/gcs/files/5aa37f4f867ad6f1d5ab710f67f6cfdd.jpg?w=500&auto=format",
        description:
          "It's a metaverse built by wizards. From just a strand of hair to the entire world. We are not just a meme, we are a culture strongly rooted by our community. ",
        externalUrl: "https://astrandofhair.xyz/",
        twitterUsername: "Hair_xyz",
        lastIngestedAt: "2023-02-23T08:27:10.000Z",
      },
      contractDeployer: "0xc4c2a776a352a8994be83d2ef2bb4a9604dc6e97",
      deployedBlockNumber: 15210942,
    },
    tokenId: "23",
    tokenType: "ERC721",
    title: "AStrandOfHair #23",
    description: "",
    timeLastUpdated: "2023-02-17T07:41:29.358Z",
    rawMetadata: {
      name: "AStrandOfHair #23",
      description: "",
      image: "ipfs://QmS813MTWh2N8zJH3edrYDVUrVX5WfPraDiK1119tXow8V/23.png",
      attributes: [
        {
          value: "rufous",
          trait_type: "Background",
        },
        {
          value: "ash green",
          trait_type: "Shadow",
        },
        {
          value: "alverta",
          trait_type: "Witch",
        },
        {
          value: "light green",
          trait_type: "Smag",
        },
        {
          value: "snake and ghost",
          trait_type: "Pot",
        },
        {
          value: "purple - will-o'-the-wisp",
          trait_type: "Soul",
        },
        {
          value: "hallowmas",
          trait_type: "Medium",
        },
        {
          value: "taupe - nude goblin",
          trait_type: "Stealer",
        },
        {
          value: "purple - sea snail",
          trait_type: "Loot",
        },
        {
          value: "orange - serrated hair",
          trait_type: "Hair",
        },
      ],
    },
    tokenUri: {
      gateway:
        "https://ipfs.io/ipfs/QmTUnRhkS1f5TxY1tCJMYhG2igkjVhKsppYYBNpPv4bSvN/23.json",
      raw: "ipfs://QmTUnRhkS1f5TxY1tCJMYhG2igkjVhKsppYYBNpPv4bSvN/23.json",
    },
    media: [
      {
        gateway:
          "https://nft-cdn.alchemy.com/eth-mainnet/5868c442a98977f04f029d8af1800a67",
        thumbnail:
          "https://res.cloudinary.com/alchemyapi/image/upload/thumbnailv2/eth-mainnet/5868c442a98977f04f029d8af1800a67",
        raw: "ipfs://QmS813MTWh2N8zJH3edrYDVUrVX5WfPraDiK1119tXow8V/23.png",
        format: "png",
        bytes: 2778017,
      },
    ],
    balance: 1,
  },
  {
    contract: {
      address: "0x82cb9d20862641301c987f0b096086d32bc11b65",
      name: "AStrandOfHair",
      symbol: "ASOH",
      totalSupply: "10358",
      tokenType: "ERC721",
      openSea: {
        floorPrice: 0,
        collectionName: "AStrandOfHair",
        safelistRequestStatus: "approved",
        imageUrl:
          "https://i.seadn.io/gcs/files/5aa37f4f867ad6f1d5ab710f67f6cfdd.jpg?w=500&auto=format",
        description:
          "It's a metaverse built by wizards. From just a strand of hair to the entire world. We are not just a meme, we are a culture strongly rooted by our community. ",
        externalUrl: "https://astrandofhair.xyz/",
        twitterUsername: "Hair_xyz",
        lastIngestedAt: "2023-02-23T08:27:10.000Z",
      },
      contractDeployer: "0xc4c2a776a352a8994be83d2ef2bb4a9604dc6e97",
      deployedBlockNumber: 15210942,
    },
    tokenId: "24",
    tokenType: "ERC721",
    title: "AStrandOfHair #24",
    description: "",
    timeLastUpdated: "2023-02-17T07:17:28.990Z",
    rawMetadata: {
      name: "AStrandOfHair #24",
      description: "",
      image: "ipfs://QmS813MTWh2N8zJH3edrYDVUrVX5WfPraDiK1119tXow8V/24.png",
      attributes: [
        {
          value: "rufous",
          trait_type: "Background",
        },
        {
          value: "black",
          trait_type: "Shadow",
        },
        {
          value: "ishmerai",
          trait_type: "Witch",
        },
        {
          value: "purple",
          trait_type: "Smag",
        },
        {
          value: "olla",
          trait_type: "Pot",
        },
        {
          value: "purple - eyeball",
          trait_type: "Soul",
        },
        {
          value: "candle",
          trait_type: "Medium",
        },
        {
          value: "purple - goblin in the vehicle",
          trait_type: "Stealer",
        },
        {
          value: "green - agentia",
          trait_type: "Loot",
        },
        {
          value: "green - bacterial hair",
          trait_type: "Hair",
        },
      ],
    },
    tokenUri: {
      gateway:
        "https://ipfs.io/ipfs/QmTUnRhkS1f5TxY1tCJMYhG2igkjVhKsppYYBNpPv4bSvN/24.json",
      raw: "ipfs://QmTUnRhkS1f5TxY1tCJMYhG2igkjVhKsppYYBNpPv4bSvN/24.json",
    },
    media: [
      {
        gateway:
          "https://nft-cdn.alchemy.com/eth-mainnet/9a5ceaa21a45454403c67cdcbc27f620",
        thumbnail:
          "https://res.cloudinary.com/alchemyapi/image/upload/thumbnailv2/eth-mainnet/9a5ceaa21a45454403c67cdcbc27f620",
        raw: "ipfs://QmS813MTWh2N8zJH3edrYDVUrVX5WfPraDiK1119tXow8V/24.png",
        format: "png",
        bytes: 2760882,
      },
    ],
    balance: 1,
  },
  {
    contract: {
      address: "0x82cb9d20862641301c987f0b096086d32bc11b65",
      name: "AStrandOfHair",
      symbol: "ASOH",
      totalSupply: "10358",
      tokenType: "ERC721",
      openSea: {
        floorPrice: 0,
        collectionName: "AStrandOfHair",
        safelistRequestStatus: "approved",
        imageUrl:
          "https://i.seadn.io/gcs/files/5aa37f4f867ad6f1d5ab710f67f6cfdd.jpg?w=500&auto=format",
        description:
          "It's a metaverse built by wizards. From just a strand of hair to the entire world. We are not just a meme, we are a culture strongly rooted by our community. ",
        externalUrl: "https://astrandofhair.xyz/",
        twitterUsername: "Hair_xyz",
        lastIngestedAt: "2023-02-23T08:27:10.000Z",
      },
      contractDeployer: "0xc4c2a776a352a8994be83d2ef2bb4a9604dc6e97",
      deployedBlockNumber: 15210942,
    },
    tokenId: "25",
    tokenType: "ERC721",
    title: "AStrandOfHair #25",
    description: "",
    timeLastUpdated: "2023-02-26T15:15:29.456Z",
    rawMetadata: {
      name: "AStrandOfHair #25",
      description: "",
      image: "ipfs://QmS813MTWh2N8zJH3edrYDVUrVX5WfPraDiK1119tXow8V/25.png",
      attributes: [
        {
          value: "caramel green",
          trait_type: "Background",
        },
        {
          value: "dark purple",
          trait_type: "Shadow",
        },
        {
          value: "dayvee",
          trait_type: "Witch",
        },
        {
          value: "teethyblow gray",
          trait_type: "Smag",
        },
        {
          value: "agentia",
          trait_type: "Pot",
        },
        {
          value: "brown bubble",
          trait_type: "Soul",
        },
        {
          value: "friar's lantern",
          trait_type: "Medium",
        },
        {
          value: "nude goblin with hat",
          trait_type: "Stealer",
        },
        {
          value: "wizard hat",
          trait_type: "Loot",
        },
        {
          value: "pale green - bacterial hair",
          trait_type: "Hair",
        },
      ],
    },
    tokenUri: {
      gateway:
        "https://ipfs.io/ipfs/QmTUnRhkS1f5TxY1tCJMYhG2igkjVhKsppYYBNpPv4bSvN/25.json",
      raw: "ipfs://QmTUnRhkS1f5TxY1tCJMYhG2igkjVhKsppYYBNpPv4bSvN/25.json",
    },
    media: [
      {
        gateway:
          "https://nft-cdn.alchemy.com/eth-mainnet/5f471c95fe24a2f91356ad674d2b39f8",
        thumbnail:
          "https://res.cloudinary.com/alchemyapi/image/upload/thumbnailv2/eth-mainnet/5f471c95fe24a2f91356ad674d2b39f8",
        raw: "ipfs://QmS813MTWh2N8zJH3edrYDVUrVX5WfPraDiK1119tXow8V/25.png",
        format: "png",
        bytes: 2589418,
      },
    ],
    balance: 1,
  },
  {
    contract: {
      address: "0x82cb9d20862641301c987f0b096086d32bc11b65",
      name: "AStrandOfHair",
      symbol: "ASOH",
      totalSupply: "10358",
      tokenType: "ERC721",
      openSea: {
        floorPrice: 0,
        collectionName: "AStrandOfHair",
        safelistRequestStatus: "approved",
        imageUrl:
          "https://i.seadn.io/gcs/files/5aa37f4f867ad6f1d5ab710f67f6cfdd.jpg?w=500&auto=format",
        description:
          "It's a metaverse built by wizards. From just a strand of hair to the entire world. We are not just a meme, we are a culture strongly rooted by our community. ",
        externalUrl: "https://astrandofhair.xyz/",
        twitterUsername: "Hair_xyz",
        lastIngestedAt: "2023-02-23T08:27:10.000Z",
      },
      contractDeployer: "0xc4c2a776a352a8994be83d2ef2bb4a9604dc6e97",
      deployedBlockNumber: 15210942,
    },
    tokenId: "26",
    tokenType: "ERC721",
    title: "AStrandOfHair #26",
    description: "",
    timeLastUpdated: "2023-03-05T05:40:39.319Z",
    rawMetadata: {
      name: "AStrandOfHair #26",
      description: "",
      image: "ipfs://QmS813MTWh2N8zJH3edrYDVUrVX5WfPraDiK1119tXow8V/26.png",
      attributes: [
        {
          value: "sepia",
          trait_type: "Background",
        },
        {
          value: "olive gray",
          trait_type: "Shadow",
        },
        {
          value: "gerold",
          trait_type: "Witch",
        },
        {
          value: "ice blue",
          trait_type: "Smag",
        },
        {
          value: "mushroom",
          trait_type: "Pot",
        },
        {
          value: "purple - eyeball",
          trait_type: "Soul",
        },
        {
          value: "oil lamp",
          trait_type: "Medium",
        },
        {
          value: "nude goblin has a beard",
          trait_type: "Stealer",
        },
        {
          value: "beggar",
          trait_type: "Loot",
        },
        {
          value: "green - vascular hair",
          trait_type: "Hair",
        },
      ],
    },
    tokenUri: {
      gateway:
        "https://ipfs.io/ipfs/QmTUnRhkS1f5TxY1tCJMYhG2igkjVhKsppYYBNpPv4bSvN/26.json",
      raw: "ipfs://QmTUnRhkS1f5TxY1tCJMYhG2igkjVhKsppYYBNpPv4bSvN/26.json",
    },
    media: [
      {
        gateway:
          "https://nft-cdn.alchemy.com/eth-mainnet/ecd3eff55773a5129decd5f0c858bda5",
        thumbnail:
          "https://res.cloudinary.com/alchemyapi/image/upload/thumbnailv2/eth-mainnet/ecd3eff55773a5129decd5f0c858bda5",
        raw: "ipfs://QmS813MTWh2N8zJH3edrYDVUrVX5WfPraDiK1119tXow8V/26.png",
        format: "png",
        bytes: 2437552,
      },
    ],
    balance: 1,
  },
  {
    contract: {
      address: "0x82cb9d20862641301c987f0b096086d32bc11b65",
      name: "AStrandOfHair",
      symbol: "ASOH",
      totalSupply: "10358",
      tokenType: "ERC721",
      openSea: {
        floorPrice: 0,
        collectionName: "AStrandOfHair",
        safelistRequestStatus: "approved",
        imageUrl:
          "https://i.seadn.io/gcs/files/5aa37f4f867ad6f1d5ab710f67f6cfdd.jpg?w=500&auto=format",
        description:
          "It's a metaverse built by wizards. From just a strand of hair to the entire world. We are not just a meme, we are a culture strongly rooted by our community. ",
        externalUrl: "https://astrandofhair.xyz/",
        twitterUsername: "Hair_xyz",
        lastIngestedAt: "2023-02-23T08:27:10.000Z",
      },
      contractDeployer: "0xc4c2a776a352a8994be83d2ef2bb4a9604dc6e97",
      deployedBlockNumber: 15210942,
    },
    tokenId: "27",
    tokenType: "ERC721",
    title: "AStrandOfHair #27",
    description: "",
    timeLastUpdated: "2023-01-22T04:49:35.942Z",
    rawMetadata: {
      name: "AStrandOfHair #27",
      description: "",
      image: "ipfs://QmS813MTWh2N8zJH3edrYDVUrVX5WfPraDiK1119tXow8V/27.png",
      attributes: [
        {
          value: "blackish green",
          trait_type: "Background",
        },
        {
          value: "coffee",
          trait_type: "Shadow",
        },
        {
          value: "ebbo",
          trait_type: "Witch",
        },
        {
          value: "brilliant green",
          trait_type: "Smag",
        },
        {
          value: "copper",
          trait_type: "Pot",
        },
        {
          value: "symbol",
          trait_type: "Soul",
        },
        {
          value: "agentia",
          trait_type: "Medium",
        },
        {
          value: "dusty blue - nude gobin",
          trait_type: "Stealer",
        },
        {
          value: "beggar",
          trait_type: "Loot",
        },
        {
          value: "prasinous - tragi",
          trait_type: "Hair",
        },
      ],
    },
    tokenUri: {
      gateway:
        "https://ipfs.io/ipfs/QmTUnRhkS1f5TxY1tCJMYhG2igkjVhKsppYYBNpPv4bSvN/27.json",
      raw: "ipfs://QmTUnRhkS1f5TxY1tCJMYhG2igkjVhKsppYYBNpPv4bSvN/27.json",
    },
    media: [
      {
        gateway:
          "https://nft-cdn.alchemy.com/eth-mainnet/4a9e5ab5a94449b87f850253d8f54e1c",
        thumbnail:
          "https://res.cloudinary.com/alchemyapi/image/upload/thumbnailv2/eth-mainnet/4a9e5ab5a94449b87f850253d8f54e1c",
        raw: "ipfs://QmS813MTWh2N8zJH3edrYDVUrVX5WfPraDiK1119tXow8V/27.png",
        format: "png",
        bytes: 2651108,
      },
    ],
    balance: 1,
  },
  {
    contract: {
      address: "0x82cb9d20862641301c987f0b096086d32bc11b65",
      name: "AStrandOfHair",
      symbol: "ASOH",
      totalSupply: "10358",
      tokenType: "ERC721",
      openSea: {
        floorPrice: 0,
        collectionName: "AStrandOfHair",
        safelistRequestStatus: "approved",
        imageUrl:
          "https://i.seadn.io/gcs/files/5aa37f4f867ad6f1d5ab710f67f6cfdd.jpg?w=500&auto=format",
        description:
          "It's a metaverse built by wizards. From just a strand of hair to the entire world. We are not just a meme, we are a culture strongly rooted by our community. ",
        externalUrl: "https://astrandofhair.xyz/",
        twitterUsername: "Hair_xyz",
        lastIngestedAt: "2023-02-23T08:27:10.000Z",
      },
      contractDeployer: "0xc4c2a776a352a8994be83d2ef2bb4a9604dc6e97",
      deployedBlockNumber: 15210942,
    },
    tokenId: "28",
    tokenType: "ERC721",
    title: "AStrandOfHair #28",
    description: "",
    timeLastUpdated: "2023-01-15T07:43:31.515Z",
    rawMetadata: {
      name: "AStrandOfHair #28",
      description: "",
      image: "ipfs://QmS813MTWh2N8zJH3edrYDVUrVX5WfPraDiK1119tXow8V/28.png",
      attributes: [
        {
          value: "prussian blue",
          trait_type: "Background",
        },
        {
          value: "black",
          trait_type: "Shadow",
        },
        {
          value: "dayvee",
          trait_type: "Witch",
        },
        {
          value: "powder blue",
          trait_type: "Smag",
        },
        {
          value: "candle",
          trait_type: "Pot",
        },
        {
          value: "lightning",
          trait_type: "Soul",
        },
        {
          value: "hallowmas",
          trait_type: "Medium",
        },
        {
          value: "happy goblin",
          trait_type: "Stealer",
        },
        {
          value: "purple - diamond",
          trait_type: "Loot",
        },
        {
          value: "purple - hair root",
          trait_type: "Hair",
        },
      ],
    },
    tokenUri: {
      gateway:
        "https://ipfs.io/ipfs/QmTUnRhkS1f5TxY1tCJMYhG2igkjVhKsppYYBNpPv4bSvN/28.json",
      raw: "ipfs://QmTUnRhkS1f5TxY1tCJMYhG2igkjVhKsppYYBNpPv4bSvN/28.json",
    },
    media: [
      {
        gateway:
          "https://nft-cdn.alchemy.com/eth-mainnet/204177a74649ce0226222e2ea431c468",
        thumbnail:
          "https://res.cloudinary.com/alchemyapi/image/upload/thumbnailv2/eth-mainnet/204177a74649ce0226222e2ea431c468",
        raw: "ipfs://QmS813MTWh2N8zJH3edrYDVUrVX5WfPraDiK1119tXow8V/28.png",
        format: "png",
        bytes: 2923827,
      },
    ],
    balance: 1,
  },
  {
    contract: {
      address: "0x82cb9d20862641301c987f0b096086d32bc11b65",
      name: "AStrandOfHair",
      symbol: "ASOH",
      totalSupply: "10358",
      tokenType: "ERC721",
      openSea: {
        floorPrice: 0,
        collectionName: "AStrandOfHair",
        safelistRequestStatus: "approved",
        imageUrl:
          "https://i.seadn.io/gcs/files/5aa37f4f867ad6f1d5ab710f67f6cfdd.jpg?w=500&auto=format",
        description:
          "It's a metaverse built by wizards. From just a strand of hair to the entire world. We are not just a meme, we are a culture strongly rooted by our community. ",
        externalUrl: "https://astrandofhair.xyz/",
        twitterUsername: "Hair_xyz",
        lastIngestedAt: "2023-02-23T08:27:10.000Z",
      },
      contractDeployer: "0xc4c2a776a352a8994be83d2ef2bb4a9604dc6e97",
      deployedBlockNumber: 15210942,
    },
    tokenId: "29",
    tokenType: "ERC721",
    title: "AStrandOfHair #29",
    description: "",
    timeLastUpdated: "2022-11-30T00:03:59.709Z",
    rawMetadata: {
      name: "AStrandOfHair #29",
      description: "",
      image: "ipfs://QmS813MTWh2N8zJH3edrYDVUrVX5WfPraDiK1119tXow8V/29.png",
      attributes: [
        {
          value: "rufous",
          trait_type: "Background",
        },
        {
          value: "brown",
          trait_type: "Shadow",
        },
        {
          value: "harcar",
          trait_type: "Witch",
        },
        {
          value: "ice blue",
          trait_type: "Smag",
        },
        {
          value: "stone and lightning",
          trait_type: "Pot",
        },
        {
          value: "insect",
          trait_type: "Soul",
        },
        {
          value: "octopus feet",
          trait_type: "Medium",
        },
        {
          value: "purple - stealer gagtooth stealer",
          trait_type: "Stealer",
        },
        {
          value: "olive green - sea snail",
          trait_type: "Loot",
        },
        {
          value: "bluish violet - tissue hair",
          trait_type: "Hair",
        },
      ],
    },
    tokenUri: {
      gateway:
        "https://ipfs.io/ipfs/QmTUnRhkS1f5TxY1tCJMYhG2igkjVhKsppYYBNpPv4bSvN/29.json",
      raw: "ipfs://QmTUnRhkS1f5TxY1tCJMYhG2igkjVhKsppYYBNpPv4bSvN/29.json",
    },
    media: [
      {
        gateway:
          "https://nft-cdn.alchemy.com/eth-mainnet/1d8890818746633348a11d0dd02772e3",
        thumbnail:
          "https://res.cloudinary.com/alchemyapi/image/upload/thumbnailv2/eth-mainnet/1d8890818746633348a11d0dd02772e3",
        raw: "ipfs://QmS813MTWh2N8zJH3edrYDVUrVX5WfPraDiK1119tXow8V/29.png",
        format: "png",
        bytes: 2592331,
      },
    ],
    balance: 1,
  },
  {
    contract: {
      address: "0x8fa600364b93c53e0c71c7a33d2ade21f4351da3",
      name: "Larva Chads",
      symbol: "LChads",
      totalSupply: "5000",
      tokenType: "ERC721",
      openSea: {
        floorPrice: 0.086,
        collectionName: "Larva Chads",
        safelistRequestStatus: "approved",
        imageUrl:
          "https://i.seadn.io/gae/9ELTIcN5R3W4Im2vWAQSOf77wyr_6KPrJoKRL9gqszYN_3Ut7pBdB2XGQwTR4Si2c0n6jbAm30t8_e2__gUXpCWG8DhaiTExyzQW?w=500&auto=format",
        description:
          "5000 randomly generated Larva Chads on the Ethereum blockchain. \nCC0. No roadmap, just chonky Chads. | [Honorary Chads](https://opensea.io/collection/honorary-chads).",
        externalUrl: "https://www.larvachads.com/",
        twitterUsername: "larvachads",
        discordUrl: "https://discord.gg/5aMzVJHNc2",
        lastIngestedAt: "2023-02-23T15:11:21.000Z",
      },
      contractDeployer: "0x515278483d7888b877f605984bf7ff0f489d6b88",
      deployedBlockNumber: 13933680,
    },
    tokenId: "512",
    tokenType: "ERC721",
    title: "Larva Chads #512",
    description: "Larva Chads are a play on the CryptoPunks and Larva Lads.",
    timeLastUpdated: "2023-03-01T17:36:07.840Z",
    rawMetadata: {
      name: "Larva Chads #512",
      description: "Larva Chads are a play on the CryptoPunks and Larva Lads.",
      image: "ipfs://QmQZyeyrd8AQVwQF93axb9CssfsNuGXmGxXdCN74mFux3h/512.png",
      edition: 512,
      attributes: [
        {
          value: "Normal",
          trait_type: "Type",
        },
        {
          value: "Normal",
          trait_type: "Face",
        },
        {
          value: "None",
          trait_type: "Accessory 1",
        },
        {
          value: "Cowboy",
          trait_type: "Headwear",
        },
        {
          value: "Small Shades",
          trait_type: "Eyewear",
        },
        {
          value: "Earring",
          trait_type: "Accessory 2",
        },
      ],
    },
    tokenUri: {
      gateway:
        "https://ipfs.io/ipfs/QmRW9DN4LLwuACekDGyDJtQrJaTiKmhx7F5DkLe8ei2Hw5/512",
      raw: "ipfs://QmRW9DN4LLwuACekDGyDJtQrJaTiKmhx7F5DkLe8ei2Hw5/512",
    },
    media: [
      {
        gateway:
          "https://nft-cdn.alchemy.com/eth-mainnet/54be792994df790a315619bcda082923",
        thumbnail:
          "https://res.cloudinary.com/alchemyapi/image/upload/thumbnailv2/eth-mainnet/54be792994df790a315619bcda082923",
        raw: "ipfs://QmQZyeyrd8AQVwQF93axb9CssfsNuGXmGxXdCN74mFux3h/512.png",
        format: "png",
        bytes: 1810,
      },
    ],
    balance: 1,
  },
  {
    contract: {
      address: "0x9508f760833b82cdfc030d66aa278c296e013f57",
      name: "VAYC",
      symbol: "VAYC",
      totalSupply: "9999",
      tokenType: "ERC721",
      openSea: {
        floorPrice: 0.00899,
        collectionName: "V.A.Y.C",
        imageUrl:
          "https://i.seadn.io/gae/fHDsxxuru4x9d0PcAno5BNiUpF65WLxFYmF2Ewu1y7wUvjQS3TpRbvf8C8Z8qQwocM41syhzPgG2YKiPECZF20PC3J4R7-_PfE7RVw?w=500&auto=format",
        description:
          "This experiment has reversed the effects of the infamous serum and spawned 10,000 brand new, never before seen apes, each corresponding to their living genesis mutant counterpart. Now all mutants can walk amongst the apes as equals.\r\n\r\nNot affiliated with any other NFT projects.",
        externalUrl: "https://vayc.art/",
        twitterUsername: "VAYCNFT",
        discordUrl: "https://discord.gg/kdAMtKJ98x",
        lastIngestedAt: "2023-02-24T00:09:16.000Z",
      },
      contractDeployer: "0xf2a5d6820bd2a384575b9f286a35c66fdde7b54b",
      deployedBlockNumber: 14116334,
    },
    tokenId: "2056",
    tokenType: "ERC721",
    title: "V.A.Y.C #6589",
    description: "",
    timeLastUpdated: "2023-01-18T04:09:34.616Z",
    rawMetadata: {
      name: "V.A.Y.C #6589",
      image: "ipfs://QmX6xvMnb7X3TRQSJZV2zKJpne4PqncZoYhjeJxBx1KpCh",
      attributes: [
        {
          value: "Sleepy",
          trait_type: "Eyes",
        },
        {
          value: "Bored Cigarette",
          trait_type: "Mouth",
        },
        {
          value: "Ww2 Pilot Helm",
          trait_type: "Hat",
        },
        {
          value: "Space Suit",
          trait_type: "Clothes",
        },
        {
          value: "New Punk Blue",
          trait_type: "Background",
        },
        {
          value: "Dark Brown",
          trait_type: "Fur",
        },
      ],
    },
    tokenUri: {
      gateway:
        "https://ipfs.io/ipfs/QmeTKvcrsy4EQSFMNKctjJ2k47gkAjVhobSACbCDwFjTLH/2056.json",
      raw: "ipfs://QmeTKvcrsy4EQSFMNKctjJ2k47gkAjVhobSACbCDwFjTLH/2056.json",
    },
    media: [
      {
        gateway:
          "https://nft-cdn.alchemy.com/eth-mainnet/7c7d28fe8bcf9240e3c9ca072d3e036d",
        thumbnail:
          "https://res.cloudinary.com/alchemyapi/image/upload/thumbnailv2/eth-mainnet/7c7d28fe8bcf9240e3c9ca072d3e036d",
        raw: "ipfs://QmX6xvMnb7X3TRQSJZV2zKJpne4PqncZoYhjeJxBx1KpCh",
        format: "png",
        bytes: 133309,
      },
    ],
    spamInfo: {
      isSpam: true,
      classifications: [
        "Erc721TooManyOwners",
        "Erc721TooManyTokens",
        "HoneyPotsOwnMultipleTokens",
      ],
    },
    balance: 1,
  },
  {
    contract: {
      address: "0xdb55584e5104505a6b38776ee4dcba7dd6bb25fe",
      name: "Visitors of Imma Degen",
      symbol: "VOID",
      tokenType: "ERC721",
      openSea: {
        floorPrice: 0.059,
        collectionName: "VOID - Visitors of Imma Degen",
        safelistRequestStatus: "verified",
        imageUrl:
          "https://i.seadn.io/gae/ykrl73bgMzN8pfYhpTf2g2ayRHBQ-8Ga8pQyjSk06QUXk2DArZhkOfl-dIf3S2PjofZ4i5igYtp4pXJDZFomLSMphwf6Jdbsoj0NoA?w=500&auto=format",
        description:
          "#First one to be more than just a pfp.   \nEvery VOID comes with a metaverse-ready avatar/3D model.    \nEndless Gamification.   \nCommercial Rights.   \nBuild a brand around your VOID.   \n**Social Media Zoom Integration & More**.   \nJoin us on [Discord](https://discord.gg/immaverse) for more info!   ",
        externalUrl: "https://www.immadegen.com/",
        twitterUsername: "ImmaDegen",
        discordUrl: "https://discord.gg/rz6t3uP9hx",
        lastIngestedAt: "2023-02-26T09:37:34.000Z",
      },
      contractDeployer: "0x0803a4269c68bdc545771a481278285a0a1ccc9c",
      deployedBlockNumber: 12747038,
    },
    tokenId: "3906",
    tokenType: "ERC721",
    title: "",
    description: "",
    timeLastUpdated: "2023-03-05T06:52:39.115Z",
    rawMetadata: {
      token_id: 3906,
      image: "https://void-explorer.netlify.app/void_images/image3906.png",
      attributes: [
        {
          value: "Navy",
          trait_type: "Eyes",
        },
        {
          value: "Hoodie with Jacket",
          trait_type: "Clothing",
        },
        {
          value: "Round Glasses",
          trait_type: "Eyewear",
        },
        {
          value: "Pipe",
          trait_type: "Mouth",
        },
        {
          value: "Clown",
          trait_type: "Nose",
        },
        {
          value: "Green",
          trait_type: "Background",
        },
        {
          value: "Surprised",
          trait_type: "Expression",
        },
        {
          value: "Green",
          trait_type: "Skin",
        },
      ],
    },
    tokenUri: {
      gateway: "https://void-explorer.netlify.app/void_metadata/3906",
      raw: "https://void-explorer.netlify.app/void_metadata/3906",
    },
    media: [
      {
        gateway:
          "https://nft-cdn.alchemy.com/eth-mainnet/a4e3087440aab9bc08a0459783caa967",
        thumbnail:
          "https://res.cloudinary.com/alchemyapi/image/upload/thumbnailv2/eth-mainnet/a4e3087440aab9bc08a0459783caa967",
        raw: "https://void-explorer.netlify.app/void_images/image3906.png",
        format: "jpeg",
        bytes: 188954,
      },
    ],
    balance: 1,
  },
  {
    contract: {
      address: "0xf4da069c1eb871923416b499adab024737f2f742",
      name: "WallstreetNFTs",
      symbol: "CHAMP",
      totalSupply: "2877",
      tokenType: "ERC721",
      openSea: {
        floorPrice: 0.000959,
        collectionName: "DA CHAMPS",
        safelistRequestStatus: "not_requested",
        imageUrl:
          "https://i.seadn.io/gae/3BOG2xeggVBX-eQc_AF-Ente9NfNc6EhIkxiRI0KSUJ9PbGdi49BOox0J4tmzXfIxkw1tlulZ5nziLLA7jOTaZfkxwai3nPhl47T6A?w=500&auto=format",
        description:
          "Da Champs live to trade! FREE MINT IS LIVE at https://dachamps.com/",
        externalUrl: "https://DaChamps.com",
        twitterUsername: "DaChampsNFT",
        discordUrl: "https://discord.gg/yXD2EBZnu5",
        lastIngestedAt: "2023-02-27T02:41:20.000Z",
      },
      contractDeployer: "0x996787308cdd691f36bbd4064c81babb56081e58",
      deployedBlockNumber: 13535273,
    },
    tokenId: "281",
    tokenType: "ERC721",
    title: "#281",
    description:
      "Da Champs are a group of portfolio managers buying and selling on the blockchain. Living silver spoon to mouth, day to day trade. Burning the candlestick charts on both ends.",
    timeLastUpdated: "2023-02-10T14:47:28.606Z",
    rawMetadata: {
      name: "#281",
      description:
        "Da Champs are a group of portfolio managers buying and selling on the blockchain. Living silver spoon to mouth, day to day trade. Burning the candlestick charts on both ends.",
      image:
        "https://wallstreetnfts-champs.nyc3.cdn.digitaloceanspaces.com/images/281.jpg",
      attributes: [
        {
          value: "Living Coral",
          trait_type: "Background Color",
        },
        {
          value: "White",
          trait_type: "Skin Color",
        },
        {
          value: "Pink",
          trait_type: "Shirt",
        },
        {
          value: "No suspenders",
          trait_type: "Suspenders",
        },
        {
          value: "No tie",
          trait_type: "Tie",
        },
        {
          value: "Blue",
          trait_type: "Suit",
        },
        {
          value: "Slicked brown",
          trait_type: "Hair",
        },
        {
          value: "No facial hair",
          trait_type: "Facial hair",
        },
        {
          value: "No hat",
          trait_type: "Hat",
        },
        {
          value: "Open",
          trait_type: "Eyes",
        },
        {
          value: "No eyewear",
          trait_type: "Eyewear",
        },
        {
          value: "No pinky ring",
          trait_type: "Pinky ring",
        },
        {
          value: "No scarf",
          trait_type: "Scarf",
        },
        {
          value: "No watch",
          trait_type: "Wristwear",
        },
        {
          value: "Grin",
          trait_type: "Mouth",
        },
        {
          value: "No mouthpiece",
          trait_type: "Mouthpiece",
        },
        {
          value: "Gold dollar sign",
          trait_type: "Earring",
        },
        {
          value: "No mask",
          trait_type: "Mask",
        },
      ],
    },
    tokenUri: {
      gateway:
        "https://wallstreetnfts-champs.nyc3.cdn.digitaloceanspaces.com/metadata/281",
      raw: "https://wallstreetnfts-champs.nyc3.cdn.digitaloceanspaces.com/metadata/281",
    },
    media: [
      {
        gateway:
          "https://nft-cdn.alchemy.com/eth-mainnet/653bc9def1a6b189f3d352abd0ffbff2",
        thumbnail:
          "https://res.cloudinary.com/alchemyapi/image/upload/thumbnailv2/eth-mainnet/653bc9def1a6b189f3d352abd0ffbff2",
        raw: "https://wallstreetnfts-champs.nyc3.cdn.digitaloceanspaces.com/images/281.jpg",
        format: "jpeg",
        bytes: 74999,
      },
    ],
    balance: 1,
  },
];
